"use client";

import { useMemo, useState } from "react";
import type { BaDecision, BaDecisionReasonCode, MetricComparison, RuleEvaluation, TrendSignal } from "@shop-health/domain";
import styles from "./v1-decision-workspace.module.css";

type ShopFixture = { id: string; profile: string; shop: string; state: "READY" | "LOGIN_REQUIRED" | "UNVERIFIED"; health: "Healthy" | "At risk" | "Data blocked"; operationalExposure: string; officialOnHold: string; delivery: string; trend: "TRIGGERED" | "NOT_TRIGGERED" | "NOT_EVALUATED"; rule: "CONTINUE" | "PAUSE" | "INSUFFICIENT_DATA"; ai: "SCALE" | "WATCH" | "PAUSE" | "UNAVAILABLE"; ba: "CONTINUE" | "WATCH" | "PAUSE" | "Not reviewed"; attention: string[] };
const comparisons = [{ metric: "operationalExposure", current: "2840", previous: "3150", absoluteDelta: "-310", relativeDelta: -0.098, direction: "DECREASED", currency: "USD" }, { metric: "deliveryRate", current: 0.821, previous: 0.797, absoluteDelta: 0.024, relativeDelta: 0.03, direction: "INCREASED", currency: null }] satisfies MetricComparison[];
const trendSignals = [{ signal: "DELIVERY_DETERIORATION", comparisons: [comparisons[1]!], status: "NOT_EVALUATED", reasonCode: "POLICY_UNCONFIGURED" }] satisfies TrendSignal[];
const ruleEvidence = { result: "CONTINUE", policyVersion: "risk-policy.v1", checks: [{ metric: "operationalExposure", observedValue: "2840", threshold: "3500", operator: "GTE", result: "PASS", triggeredReason: null }, { metric: "deliveryRate", observedValue: 0.821, threshold: 0.7, operator: "LT", result: "PASS", triggeredReason: null }], triggers: [], expression: "operationalExposure >= 3500 OR deliveryRate < 0.70", evaluatedAt: "2026-08-15T09:30:00.000Z" } satisfies RuleEvaluation;
const shops: ShopFixture[] = [
  { id: "shop-031", profile: "031", shop: "Northstar Home", state: "READY", health: "Healthy", operationalExposure: "$2,840", officialOnHold: "$1,265", delivery: "82.1%", trend: "NOT_EVALUATED", rule: "CONTINUE", ai: "WATCH", ba: "Not reviewed", attention: ["AI WATCH", "Human review required"] },
  { id: "shop-118", profile: "118", shop: "Hearth & Loom", state: "READY", health: "At risk", operationalExposure: "$4,920", officialOnHold: "$2,110", delivery: "66.4%", trend: "TRIGGERED", rule: "PAUSE", ai: "PAUSE", ba: "PAUSE", attention: ["Rule PAUSE", "AI PAUSE"] },
  { id: "shop-224", profile: "224", shop: "Morrow Supply", state: "LOGIN_REQUIRED", health: "Data blocked", operationalExposure: "Unknown", officialOnHold: "Unknown", delivery: "Unknown", trend: "NOT_EVALUATED", rule: "INSUFFICIENT_DATA", ai: "UNAVAILABLE", ba: "Not reviewed", attention: ["AI unavailable", "Data incomplete", "Sync attention"] },
  { id: "shop-486", profile: "486", shop: "Moss Market", state: "UNVERIFIED", health: "Data blocked", operationalExposure: "Unknown", officialOnHold: "Unknown", delivery: "Unknown", trend: "NOT_EVALUATED", rule: "INSUFFICIENT_DATA", ai: "UNAVAILABLE", ba: "Not reviewed", attention: ["Verify profile"] },
  { id: "shop-611", profile: "611", shop: "Good Day Goods", state: "READY", health: "Healthy", operationalExposure: "$1,180", officialOnHold: "$430", delivery: "91.7%", trend: "NOT_TRIGGERED", rule: "CONTINUE", ai: "SCALE", ba: "CONTINUE", attention: [] },
];
const reasonCodes: BaDecisionReasonCode[] = ["HIGH_ABSOLUTE_EXPOSURE", "LOW_DELIVERY_RATE", "HIGH_VOLUME_HEALTHY", "LOW_SAMPLE_SIZE", "CARRIER_SYSTEMIC_DELAY", "RAPID_ONHOLD_GROWTH", "DELIVERY_DETERIORATION", "REFUND_SPIKE", "DATA_INCOMPLETE", "RECOVERY_TREND", "THRESHOLD_FLAPPING", "OTHER"];
const attentionCounters: Array<[string, string]> = [["AdsPower Profiles", "5"], ["Verified TikTok Shops", "3"], ["Need BA Review", "2"], ["Rule PAUSE", "1"], ["AI WATCH", "1"], ["AI PAUSE / HIGH RISK", "1"], ["Rule / AI disagreement", "1"], ["Data incomplete", "2"], ["Sync attention", "1"]];
function tone(value: string) { if (value.includes("PAUSE") || value === "At risk") return "danger"; if (value.includes("WATCH") || value.includes("Incomplete") || value === "Data blocked") return "warning"; if (value === "SCALE" || value === "Healthy" || value === "Improving" || value === "READY") return "success"; return "neutral"; }
function Badge({ children }: { children: string }) { return <span className={styles.badge} data-tone={tone(children)}>{children}</span>; }
function CompactStat({ label, value }: { label: string; value: string }) { return <article className={styles.stat}><span>{label}</span><strong>{value}</strong></article>; }

export function V1DecisionWorkspace() {
  const [selectedId, setSelectedId] = useState("shop-031"); const [checkedIds, setCheckedIds] = useState<string[]>(["shop-031", "shop-118"]); const [queueFilter, setQueueFilter] = useState("All exceptions"); const [decision, setDecision] = useState<BaDecision | "">(""); const [reason, setReason] = useState<BaDecisionReasonCode | "">(""); const [notes, setNotes] = useState(""); const [formMessage, setFormMessage] = useState(""); const [operationMessage, setOperationMessage] = useState("No operation is running. Integration D required for server actions.");
  const [history, setHistory] = useState([{ timestamp: "15 Aug 2026, 14:22 ICT", actor: "D. Nguyen", decision: "WATCH", reason: "LOW_SAMPLE_SIZE", notes: "Recheck after the next complete finance sync." }, { timestamp: "12 Aug 2026, 09:10 ICT", actor: "S. Tran", decision: "CONTINUE", reason: "RECOVERY_TREND", notes: "Delivery recovered within the proven source window." }]);
  const selected = shops.find((shop) => shop.id === selectedId) ?? shops[0]!; const queue = useMemo(() => shops.filter((shop) => shop.attention.length > 0 && (queueFilter === "All exceptions" || shop.attention.some((item) => item.includes(queueFilter)))), [queueFilter]);
  const toggle = (id: string) => setCheckedIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  function submitDecision(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!decision || !reason || (reason === "OTHER" && !notes.trim())) { setFormMessage(reason === "OTHER" ? "Notes are required when reason code is OTHER." : "Choose a decision and required reason code before submitting."); return; } setHistory((current) => [{ timestamp: "15 Aug 2026, 16:40 ICT", actor: "Current BA (fixture)", decision, reason, notes: notes.trim() || "No note provided." }, ...current]); setFormMessage("Fixture decision added to local append-only history. Integration D will persist this command."); setDecision(""); setReason(""); setNotes(""); }
  return <div className={styles.workspace}>
    <header className={styles.header}><div><p className={styles.eyebrow}>Boss UAT workspace <span>TEST / DEV FIXTURE</span></p><h1>Control Center</h1><p>Multi-shop attention, evidence, human decisions, and dry-run execution context.</p></div><div className={styles.headerMeta}><Badge>TEST / DEV FIXTURE</Badge><small>Generated 15 Aug 2026, 16:30 ICT</small></div></header>
    <section className={styles.counterGrid} aria-label="Attention counters">{attentionCounters.map(([label, value]) => <CompactStat key={label} label={label} value={value} />)}</section>
    <section className={styles.panel} aria-labelledby="profile-operations"><div className={styles.sectionHead}><div><p>Profile operations</p><h2 id="profile-operations">Select profiles, then hand off operations</h2></div><span role="status" aria-live="polite">{operationMessage}</span></div><div className={styles.operationBar}>{["OPEN", "VERIFY", "UPDATE DATA"].map((label) => <button key={label} type="button" onClick={() => setOperationMessage(`${label} requested for profile ${selected.profile}. Integration D required.`)}>{label}</button>)}<button type="button" onClick={() => setOperationMessage(`SYNC SELECTED prepared for ${checkedIds.length} profiles. Integration D required.`)}>SYNC SELECTED ({checkedIds.length})</button><button type="button" className={styles.primaryAction} onClick={() => setOperationMessage("SYNC ALL ELIGIBLE prepared. Integration D required.")}>SYNC ALL ELIGIBLE</button></div></section>
    <section className={`${styles.panel} ${styles.tablePanel}`} aria-labelledby="shop-table-heading"><div className={styles.sectionHead}><div><p>Multi-shop overview</p><h2 id="shop-table-heading">Attention is visible without collapsing decision stages</h2></div><span>Click a shop to inspect its evidence</span></div><div className={styles.tableWrap}><table><caption className="sr-only">Multi-shop health and decision overview</caption><thead><tr>{["Select", "Profile", "Shop", "Health", "Operational exposure", "Official finance on hold", "Delivery rate", "Trend", "Rule", "AI", "BA", "Attention", "Actions"].map((header) => <th key={header} scope="col">{header}</th>)}</tr></thead><tbody>{shops.map((shop) => <tr key={shop.id} data-selected={shop.id === selectedId}><td><input aria-label={`Select profile ${shop.profile}`} type="checkbox" checked={checkedIds.includes(shop.id)} onChange={() => toggle(shop.id)} /></td><td><button className={styles.linkButton} type="button" onClick={() => setSelectedId(shop.id)}>{shop.profile}<small>{shop.state}</small></button></td><td><button className={styles.linkButton} type="button" onClick={() => setSelectedId(shop.id)}>{shop.shop}</button></td><td><Badge>{shop.health}</Badge></td><td>{shop.operationalExposure}</td><td>{shop.officialOnHold}</td><td>{shop.delivery}</td><td><Badge>{shop.trend}</Badge></td><td><Badge>{shop.rule}</Badge></td><td><Badge>{shop.ai}</Badge></td><td><Badge>{shop.ba}</Badge></td><td>{shop.attention.length ? <span className={styles.attention}>{shop.attention.join(" · ")}</span> : <span className={styles.muted}>None</span>}</td><td><button type="button" className={styles.rowAction} onClick={() => { setSelectedId(shop.id); setOperationMessage(`Profile ${shop.profile} selected for review.`); }}>Review</button></td></tr>)}</tbody></table></div></section>
    <section className={styles.detailHeader} aria-label="Selected shop"><div><p>Shop Decision Center</p><h2>{selected.shop} <span>Profile {selected.profile}</span></h2><small>This view uses frozen-contract-shaped test/dev fixture data; it is not LIVE.</small></div><div className={styles.trace}><span>Rule Result <b>{selected.rule}</b></span><i>→</i><span>AI Recommendation <b>{selected.ai}</b></span><i>→</i><span>BA Decision <b>{selected.ba}</b></span><i>→</i><span>Execution <b>DRY RUN</b></span></div></section>
    <div className={styles.detailGrid}>
      <section className={styles.panel}><div className={styles.sectionHead}><div><p>Data health</p><h2>Verified source coverage</h2></div><Badge>PARTIAL</Badge></div><dl className={styles.definitionList}><div><dt>Source</dt><dd>Seller Center</dd></div><div><dt>Proven window</dt><dd>Rolling 12 months</dd></div><div><dt>Source reconciled</dt><dd>Yes</dd></div><div><dt>Freshness</dt><dd>Fresh at 15 Aug, 16:12 ICT</dd></div></dl><p className={styles.note}>Complete within the proven rolling source window is not lifetime complete.</p></section>
      <section className={styles.panel}><div className={styles.sectionHead}><div><p>Verified metrics</p><h2>Operational and finance facts</h2></div><Badge>{selected.health}</Badge></div><div className={styles.metricGrid}><CompactStat label="Operational exposure" value={selected.operationalExposure} /><CompactStat label="Official finance on hold" value={selected.officialOnHold} /><CompactStat label="Delivery rate" value={selected.delivery} /><CompactStat label="Orders in window" value="384" /></div><p className={styles.note}>Official Finance On Hold is shown separately and is not operational exposure.</p></section>
      <section className={styles.panel}><div className={styles.sectionHead}><div><p>Trend analysis</p><h2>Compared with previous window</h2></div><Badge>{selected.trend}</Badge></div><ul className={styles.factorList}><li><b>Operational Exposure</b><span>$3,150 → $2,840 · −$310</span></li><li><b>Delivery Rate</b><span>79.7% → 82.1% · +2.4 pp</span></li><li><b>Trend policy</b><span>NOT_EVALUATED · policy unconfigured</span></li></ul></section>
      <section className={styles.panel}><div className={styles.sectionHead}><div><p>Rule engine</p><h2>Deterministic evidence</h2></div><Badge>{selected.rule}</Badge></div><div className={styles.evidence}><div className={styles.evidenceHead}><span>Metric</span><span>Observed value</span><span>Threshold</span><span>Result</span></div><div><b>Operational Exposure</b><span>$2,840</span><span>GTE $3,500</span><Badge>PASS</Badge></div><div><b>Delivery Rate</b><span>82.1%</span><span>LT 70%</span><Badge>PASS</Badge></div></div><p className={styles.note}><b>Triggered reason:</b> No rule trigger recorded. <b>Policy:</b> risk-policy.v1</p></section>
      <section className={styles.panel}><div className={styles.sectionHead}><div><p>AI analysis</p><h2>Advisory assessment</h2></div><Badge>WATCH</Badge></div><div className={styles.aiSummary}><span>Recommendation <b>WATCH</b></span><span>Risk <b>MEDIUM</b></span><span>Confidence <b>78%</b></span><span>Human review <b>Required</b></span></div><h3>Supporting factors</h3><ul className={styles.factorList}><li>Delivery rate remains above the pause threshold.</li><li>Exposure is below the deterministic stop boundary.</li></ul><h3>Risk factors</h3><ul className={styles.factorList}><li>On-hold amount increased before the latest recovery window.</li></ul><p className={styles.note}><b>Reason codes:</b> RAPID_ONHOLD_GROWTH, LOW_SAMPLE_SIZE</p><p className={styles.note}><b>What would change the recommendation:</b> another complete window with stable exposure and delivery above 80%.</p></section>
      <section className={styles.panel}><div className={styles.sectionHead}><div><p>BA review</p><h2>Record a human decision</h2></div><Badge>{selected.ba}</Badge></div><form className={styles.baForm} onSubmit={submitDecision}><fieldset><legend>Decision <em>Required</em></legend><div className={styles.choiceGrid}>{(["SCALE", "CONTINUE", "WATCH", "PAUSE"] as BaDecision[]).map((value) => <label key={value}><input name="ba-decision" type="radio" value={value} checked={decision === value} onChange={() => setDecision(value)} />{value}</label>)}</div></fieldset><label>Reason code <em>Required</em><select name="reason-code" value={reason} onChange={(event) => setReason(event.target.value as BaDecisionReasonCode | "")}><option value="">Select a reason</option>{reasonCodes.map((code) => <option key={code} value={code}>{code}</option>)}</select></label><label>Notes {reason === "OTHER" ? <em>Required for OTHER</em> : <span>Optional</span>}<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label><button className={styles.primaryAction} type="submit">Submit decision</button><p role="status" aria-live="polite" className={styles.formMessage}>{formMessage || "A submission becomes an append-only revision; it never overwrites history."}</p></form></section>
      <section className={styles.panel}><div className={styles.sectionHead}><div><p>Decision history</p><h2>Append-only revisions</h2></div><span>Current: {selected.ba}</span></div><ol className={styles.history}>{history.map((entry, index) => <li key={`${entry.timestamp}-${index}`}><time>{entry.timestamp}</time><div><b>{entry.decision}</b><span>{entry.reason}</span><p>{entry.notes}</p></div><small>{entry.actor}</small></li>)}</ol></section>
      <section className={styles.panel}><div className={styles.sectionHead}><div><p>Execution</p><h2>Dry-run only</h2></div><Badge>SIMULATED</Badge></div><p className={styles.executionText}>No Seller Center action was called. Execution remains a dry-run record until an approved, auditable implementation is integrated.</p><dl className={styles.definitionList}><div><dt>Requested action</dt><dd>HOLIDAY_MODE_ON</dd></div><div><dt>Seller Center called</dt><dd>No</dd></div></dl></section>
    </div>
    <section className={styles.panel} aria-labelledby="review-queue"><div className={styles.sectionHead}><div><p>Exception and risk queue</p><h2 id="review-queue">Review Queue</h2></div><label className={styles.filterLabel}>Prioritize<select value={queueFilter} onChange={(event) => setQueueFilter(event.target.value)}><option>All exceptions</option><option>Rule PAUSE</option><option>AI WATCH</option><option>AI unavailable</option><option>Data incomplete</option></select></label></div><ul className={styles.queue}>{queue.map((shop) => <li key={shop.id}><div><b>{shop.shop}</b><span>Profile {shop.profile} · {shop.state}</span></div><p>{shop.attention.join(" · ")}</p><button type="button" onClick={() => setSelectedId(shop.id)}>Open review</button></li>)}</ul></section>
  </div>;
}
