ALTER TABLE "refresh_checkpoint_attempts" DROP CONSTRAINT "refresh_checkpoint_attempts_proxy_preflight_valid";--> statement-breakpoint
ALTER TABLE "refresh_checkpoint_attempts" ADD CONSTRAINT "refresh_checkpoint_attempts_proxy_preflight_valid" CHECK ("refresh_checkpoint_attempts"."proxy_preflight" is null or (
      jsonb_typeof("refresh_checkpoint_attempts"."proxy_preflight") = 'object'
      and jsonb_object_length("refresh_checkpoint_attempts"."proxy_preflight") = 4
      and ("refresh_checkpoint_attempts"."proxy_preflight" ?& array['status', 'latencyMs', 'exitIp', 'reasonClass'])
      and ("refresh_checkpoint_attempts"."proxy_preflight"->>'status') in ('HEALTHY', 'DEGRADED', 'UNAVAILABLE', 'UNKNOWN')
      and jsonb_typeof("refresh_checkpoint_attempts"."proxy_preflight"->'latencyMs') = 'number'
      and ("refresh_checkpoint_attempts"."proxy_preflight"->>'latencyMs')::numeric between 0 and 10000
      and mod(("refresh_checkpoint_attempts"."proxy_preflight"->>'latencyMs')::numeric, 1) = 0
      and jsonb_typeof("refresh_checkpoint_attempts"."proxy_preflight"->'exitIp') in ('string', 'null')
      and (jsonb_typeof("refresh_checkpoint_attempts"."proxy_preflight"->'exitIp') = 'null' or (
        ("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp') ~ '^(?:(?:25[0-5]|2[0-4][0-9]|1?[0-9]?[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1?[0-9]?[0-9])$'
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 0 and 16777215
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 167772160 and 184549375
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 1681915904 and 1686110207
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 2130706432 and 2147483647
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 2851995648 and 2852061183
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 2886729728 and 2887778303
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 3221225472 and 3221225727
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 3221225984 and 3221226239
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 3223307264 and 3223307519
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 3224682752 and 3224683007
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 3227017984 and 3227018239
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 3232235520 and 3232301055
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 3232706560 and 3232706815
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 3323068416 and 3323199487
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 3325256704 and 3325256959
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 3405803776 and 3405804031
         and ((split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 1)::bigint * 16777216) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 2)::bigint * 65536) + (split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 3)::bigint * 256) + split_part("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp', '.', 4)::bigint) not between 3758096384 and 4294967295
      ))
      and (
        (("refresh_checkpoint_attempts"."proxy_preflight"->>'status') = 'HEALTHY' and ("refresh_checkpoint_attempts"."proxy_preflight"->>'reasonClass') = 'OBSERVED_HEALTHY')
        or (("refresh_checkpoint_attempts"."proxy_preflight"->>'status') = 'DEGRADED' and ("refresh_checkpoint_attempts"."proxy_preflight"->>'reasonClass') = 'OBSERVED_SLOW')
        or (("refresh_checkpoint_attempts"."proxy_preflight"->>'status') = 'UNAVAILABLE' and ("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp') is null and ("refresh_checkpoint_attempts"."proxy_preflight"->>'reasonClass') in ('OBSERVED_UNAVAILABLE', 'AUTH_REJECTED', 'HTTP_REJECTED', 'REQUEST_TIMEOUT', 'NETWORK_UNAVAILABLE'))
        or (("refresh_checkpoint_attempts"."proxy_preflight"->>'status') = 'UNKNOWN' and ("refresh_checkpoint_attempts"."proxy_preflight"->>'exitIp') is null and ("refresh_checkpoint_attempts"."proxy_preflight"->>'reasonClass') = 'OBSERVATION_UNAVAILABLE')
      )
    ));