import type { AiDecisionContext } from "@shop-health/domain";
import type { BaselineAiInput } from "./contracts.js";

export const validBaselineAiInput: BaselineAiInput = {
  metricsSnapshot: {
    window: "FULL_PERSISTED_HISTORY",
    periodStart: "2026-08-01T00:00:00.000Z",
    periodEnd: "2026-08-14T00:00:00.000Z",
    totalOrders: 120,
    totalPersistedOrders: 120,
    operationalOrderCount: 100,
    onHoldOrderCount: 18,
    deliveredCount: 84,
    deliveryRate: 0.84,
    cancellationRate: null,
    refundRate: null,
    onHoldValue: "1200.0000",
    currency: "USD",
  },
  financeSnapshot: {
    capturedAt: "2026-08-14T00:00:00.000Z",
    currency: "USD",
    availableBalance: null,
    frozenBalance: null,
    totalBalance: null,
    toSettleBalance: "310.1600",
    onHoldBalance: "310.1600",
    officialOnHoldAmount: "310.1600",
    waitingForPackageDeliveryAmount: null,
    deliveredAwaitingSettlementAmount: null,
    waitingForCompletedRefundReturnAmount: "42.0000",
    reasonTotalsReconcileToOfficialOnHold: true,
    missingOnHoldExpectedAmountCount: 0,
    settlementCount: 8,
    onHoldSettlementCount: 8,
  },
  coverageSnapshot: {
    coverageState: "COMPLETE",
    persistedMetricsWindow: "FULL_PERSISTED_HISTORY",
    source: "SELLER_CENTER",
    provenSourceWindow: "ROLLING_12_MONTHS",
    completeWithinSourceWindow: true,
    lifetimeHistoryComplete: false,
    ordersSourceComplete: true,
    financeRequiredSourceComplete: true,
    sourceReconciled: true,
    latestSuccessfulSyncAt: "2026-08-14T00:00:00.000Z",
    financeCapturedAt: "2026-08-14T00:00:00.000Z",
    freshness: "FRESH",
  },
  riskSnapshot: {
    policyVersion: "risk-control-policy.v1",
    evaluatedAt: "2026-08-14T00:00:00.000Z",
    onHoldValue: "1200.0000",
    deliveryRate: 0.84,
    stopByOnHoldValue: false,
    stopByDeliveryRate: false,
    dataSufficient: true,
    stopOnHoldValueAt: "3500.0000",
    stopDeliveryRateBelow: 0.7,
    minimumOrdersForRateRule: 10,
  },
  ruleDecision: "CONTINUE",
  ruleTriggers: [],
  decisionContextSnapshot: {
    schemaVersion: "ai-decision-context.v1",
    profile: { profileId: "profile-safe-1", profileNo: "SAFE-1" },
    shop: {
      shopId: "shop-safe-1",
      tiktokShopId: null,
      displayName: "Safe Shop",
      region: "US",
      locale: "en-US",
      currency: "USD",
    },
    metrics: {
      observedAt: "2026-08-14T00:00:00.000Z",
      decision: {
        window: "FULL_PERSISTED_HISTORY",
        periodStart: "2026-08-01T00:00:00.000Z",
        periodEnd: "2026-08-14T00:00:00.000Z",
        totalOrders: 120,
        totalPersistedOrders: 120,
        operationalOrderCount: 100,
        onHoldOrderCount: 18,
        deliveredCount: 84,
        deliveryRate: 0.84,
        cancellationRate: null,
        refundRate: null,
        currency: "USD",
        operationalExposure: "1200.0000",
      },
      finance: {
        capturedAt: "2026-08-14T00:00:00.000Z",
        currency: "USD",
        availableBalance: null,
        frozenBalance: null,
        totalBalance: null,
        toSettleBalance: "310.1600",
        officialFinanceOnHold: "310.1600",
        waitingForPackageDeliveryAmount: null,
        deliveredAwaitingSettlementAmount: null,
        waitingForCompletedRefundReturnAmount: "42.0000",
        reasonTotalsReconcileToOfficialOnHold: true,
        missingOnHoldExpectedAmountCount: 0,
        settlementCount: 8,
        onHoldSettlementCount: 8,
      },
    },
    comparisons: [],
    trends: [],
    dataQuality: {
      coverage: "COMPLETE",
      source: "SELLER_CENTER",
      provenSourceWindow: "ROLLING_12_MONTHS",
      completeWithinSourceWindow: true,
      lifetimeHistoryComplete: false,
      ordersSourceComplete: true,
      financeRequiredSourceComplete: true,
      sourceReconciled: true,
      freshness: "FRESH",
      latestSuccessfulSyncAt: "2026-08-14T00:00:00.000Z",
      financeCapturedAt: "2026-08-14T00:00:00.000Z",
      blockers: [],
    },
    risk: {
      policyVersion: "risk-control-policy.v1",
      evaluatedAt: "2026-08-14T00:00:00.000Z",
      deliveryRate: 0.84,
      stopByOnHoldValue: false,
      stopByDeliveryRate: false,
      dataSufficient: true,
      stopOnHoldValueAt: "3500.0000",
      stopDeliveryRateBelow: 0.7,
      minimumOrdersForRateRule: 10,
      operationalExposure: "1200.0000",
    },
    rule: {
      result: "CONTINUE",
      policyVersion: "risk-control-policy.v1",
      checks: [
        {
          metric: "operationalExposure",
          observedValue: "1200.0000",
          threshold: "3500.0000",
          operator: "GTE",
          result: "PASS",
          triggeredReason: null,
        },
        {
          metric: "deliveryRate",
          observedValue: 0.84,
          threshold: 0.7,
          operator: "LT",
          result: "PASS",
          triggeredReason: null,
        },
      ],
      triggers: [],
      expression: "operationalExposure >= 3500 USD OR deliveryRate < 70%",
      evaluatedAt: "2026-08-14T00:00:00.000Z",
    },
    previousCompatibleSnapshot: null,
    policyVersions: {
      metricDefinitionVersion: "decision-metrics.v1",
      riskPolicyVersion: "risk-control-policy.v1",
      trendPolicyVersion: null,
    },
  } satisfies AiDecisionContext,
};
